name: flgen
description: CLI to scaffold Flutter architecture and features.
version: 0.0.1+1
homepage: https://github.com/joalmr/flgen-dart
environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  flgen: main

dependencies:
  args: ^2.4.2
